### PR TITLE
Update emulator wasm

### PR DESCRIPTION
**Pull request by 0kenx**
Updated emulator to TON v2024.01 release

### CODE REVIEW

**Comment by anton-trunov** [comment]
Why not update it to a more recent version https://github.com/ton-blockchain/ton/releases/tag/v2024.04?

**Comment by 0kenx** [comment]
Because https://github.com/tact-lang/tact-emulator/issues/13

**Comment by anton-trunov** [comment]
Oh, thanks for pointing that out, it looks like I missed that notification

**Comment by anton-trunov** [comment]
Published on NPM as v4.3.0: https://www.npmjs.com/package/@tact-lang/emulator

**Pull request merged**
